### ISSUE TITLE
Use with Poky Fido

### ISSUE THREAD

**Issue by fbertux** [errordeveloper/oe-meta-go#1]
Hi!
I'm trying to use your layer with poky version fido to build go-cross. I got some errors and I can't make compile with CGO_ENABLED="1". What version of poky or oe-core do you use? 

Cheers,

Fabio

**Comment by errordeveloper** [comment]
It could the case that changes from #2 will solve the issue for you, if so please close this or let me know otherwise.

**Comment by errordeveloper** [comment]
Many things changed, please reopen if this is still and issue with the latest code :)
